version: "3.11"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

  consumer:
    build: .
    container_name: redis-consumer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app  
    command: ["python", "app/worker/consumer.py"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped
